# Generated by Django 4.1.1 on 2022-09-10 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoFE', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='article_id',
            new_name='article',
        ),
    ]
