# Generated by Django 4.1.1 on 2022-09-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoFE', '0002_rename_article_id_images_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='imgs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
